/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_javajni_JavaJni */

#ifndef _Included_com_lichao_javajni_JavaJni
#define _Included_com_lichao_javajni_JavaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lichao_javajni_JavaJni
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_lichao_javajni_JavaJni
 * Method:    getString2FromC
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_getString2FromC
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_accessField
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_lichao_javajni_JavaJni_accessstaticField
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_lichao_javajni_JavaJni_accessMethod
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_accessStaticMethod
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_accessConstructor
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_lichao_javajni_JavaJni_accessNonvirtualMethod
  (JNIEnv *env, jobject jobj);

JNIEXPORT jstring JNICALL Java_com_lichao_javajni_JavaJni_chineseChars
  (JNIEnv *env, jobject jobj, jstring in);

#ifdef __cplusplus
}
#endif
#endif
